### ISSUE TITLE
replacing adminer with phpPgAdmin?

### ISSUE THREAD

**Issue by severfire** [rezakhademix/laravel-postgres-docker#4]
per https://hub.docker.com/_/adminer
adminer is 'DEPRECATED'

I am suggesting moving to 
https://github.com/dockage/phppgadmin
phpPgAdmin

a.

**Comment by rezakhademix** [comment]
I appreciate you bringing this to my attention.
Moving to phpPgAdmin does seem like a good idea, especially since Adminer is deprecated. I’ll take a closer look and consider implementing this transition.

In case you’d like to create a pull request for this change, you’re more than welcome to do so!

**Comment by severfire** [comment]
ah, from what i see phppgadmin seems like 'abandonware'
https://github.com/phppgadmin/phppgadmin/pulls?q=is%3Apr+is%3Aclosed

this does not look good.

**Comment by rezakhademix** [comment]
So we’re resigned to the fate of PGAdmin!

Thank you once again for your time and effort!

**Comment by severfire** [comment]
indeed. too bad phpMyAdmin can't handle postgresql
